### ISSUE TITLE
ModuleNotFoundError: No module named 'invokeai.invocation_api'

### ISSUE THREAD

**Issue by Qualzz** [blessedcoolant/invoke_bria_rmbg#1]
It seems that using Invoke 3.7 triggers this error when using the  `"1. Generate images with the browser-based interface"` options ( invoke.bat) Fresh install. 

ModuleNotFoundError: No module named 'invokeai.invocation_api'

**Comment by blessedcoolant** [comment]
The support "3.7" commit is actually to support Invoke 4.0 which is currently in RC. Should be out soon. For the time being, if you know how to do it, you can revert to the older commit. That should work fine with Invoke 3.x

**Comment by Qualzz** [comment]
Oh thank you, maybe an oversight from me, i'll try the 4.0 RC then !

**Comment by blessedcoolant** [comment]
You can find the RC here. https://github.com/invoke-ai/InvokeAI/releases/tag/v4.0.0rc1

**Comment by Qualzz** [comment]
I confirm the UX does start with the v4rc1 build. However I'm facing this error:

```
[2024-03-13 17:42:28,569]::[InvokeAI]::ERROR --> Error while invoking session 4c388ad7-3184-44bf-95c2-ab2785c529e7, invocation 6f19b0de-a1d8-45c8-bf40-91f8c22936a9 (bria_bg_remove):
'InvocationContext' object has no attribute 'services'
[2024-03-13 17:42:28,569]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "E:\Projets\AI\Stable Diffusion\Invoke\.venv\lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 160, in _process
    outputs = self._invocation.invoke_internal(
  File "E:\Projets\AI\Stable Diffusion\Invoke\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 281, in invoke_internal
    output = self.invoke(context)
  File "E:\Projets\AI\Stable Diffusion\Invoke\nodes\invoke_bria_rmbg\node\__init__.py", line 23, in invoke
    image = context.services.images.get_pil(self.image.image_name)
AttributeError: 'InvocationContext' object has no attribute 'services'. Did you mean: '_services'?
```
Workflow looks ok:
![image](https://github.com/blessedcoolant/invoke_bria_rmbg/assets/35169816/cf5e8dcc-3299-431a-b627-8134747efcd9)

I also tried just the Bria node with an input image, still the same error.

**Comment by blessedcoolant** [comment]
Fixed it. Thanks for catching. `git pull`

**Comment by Qualzz** [comment]
Fix working. Thank you for your work !

**Comment by blessedcoolant** [comment]
I've pushed a new branch that has the version that is supported by Invoke 3.x - https://github.com/blessedcoolant/invoke_bria_rmbg/tree/3.x -- Just gonna leave this here in case anyone comes looking.
